/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'priceRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
});
export const Groomer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'rating' : IDL.Nat,
  'services' : IDL.Vec(Service),
});

export const idlService = IDL.Service({
  'addGroomer' : IDL.Func([IDL.Text], [], []),
  'addServiceToGroomer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Tuple(IDL.Nat, IDL.Nat)],
      [],
      [],
    ),
  'getAllGroomers' : IDL.Func([], [IDL.Vec(Groomer)], ['query']),
  'getGroomer' : IDL.Func([IDL.Nat], [Groomer], ['query']),
  'getServicesForGroomer' : IDL.Func([IDL.Nat], [IDL.Vec(Service)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'priceRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  });
  const Groomer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'rating' : IDL.Nat,
    'services' : IDL.Vec(Service),
  });
  
  return IDL.Service({
    'addGroomer' : IDL.Func([IDL.Text], [], []),
    'addServiceToGroomer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Tuple(IDL.Nat, IDL.Nat)],
        [],
        [],
      ),
    'getAllGroomers' : IDL.Func([], [IDL.Vec(Groomer)], ['query']),
    'getGroomer' : IDL.Func([IDL.Nat], [Groomer], ['query']),
    'getServicesForGroomer' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Service)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };