/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Service = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'priceRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
});
export const Groomer = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'rating' : IDL.Nat,
  'services' : IDL.Vec(Service),
});

export const idlService = IDL.Service({
  'getAllGroomers' : IDL.Func([], [IDL.Vec(Groomer)], ['query']),
  'getGroomer' : IDL.Func([IDL.Nat], [IDL.Opt(Groomer)], ['query']),
  'registerGroomer' : IDL.Func([IDL.Text, IDL.Vec(Service)], [IDL.Nat], []),
  'updateGroomerServices' : IDL.Func([IDL.Nat, IDL.Vec(Service)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Service = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'priceRange' : IDL.Tuple(IDL.Nat, IDL.Nat),
  });
  const Groomer = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'rating' : IDL.Nat,
    'services' : IDL.Vec(Service),
  });
  
  return IDL.Service({
    'getAllGroomers' : IDL.Func([], [IDL.Vec(Groomer)], ['query']),
    'getGroomer' : IDL.Func([IDL.Nat], [IDL.Opt(Groomer)], ['query']),
    'registerGroomer' : IDL.Func([IDL.Text, IDL.Vec(Service)], [IDL.Nat], []),
    'updateGroomerServices' : IDL.Func([IDL.Nat, IDL.Vec(Service)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };